site_name: LASER # update to your project name
site_url: https://institutefordiseasemodeling.github.io/laser-generic # update to your project URL
repo_name: InstituteforDiseaseModeling/laser-generic # update to your repo name
repo_url: https://github.com/InstituteforDiseaseModeling/laser-generic # update to your repo URL
theme:
  name: material
  custom_dir: docs/customization/overrides
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/idm-logo-transparent.png
  favicon: images/favicon.ico
  features:
    - navigation.footer # include a footer with links to privacy, terms, etc.
    - content.code.copy # enable copy buttons for code blocks
    - navigation.indexes # enable parent index page for sections
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: light blue
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: light blue

nav: # Navigation structure for the documentation
  - Home: index.md
  - Software overview:
    - software-overview/index.md
    - software-overview/architecture.md
    - software-overview/scenario.md
    - Demographics:
      - software-overview/demographics/index.md
      - software-overview/demographics/age_pyramid.ipynb
      - software-overview/demographics/kmestimator.ipynb
    - software-overview/migration.md
    - software-overview/database.md
    - software-overview/transmission.md
  - Get started:
    - get-started/index.md
    - get-started/calibration.md
    - get-started/optimization.md
  - Tutorials:
    - tutorials/index.md
    - tutorials/sir.md
    - tutorials/census_tracker_sir.md
    - Notebooks:
      - SI model with no demographics: tutorials/notebooks/01_SI_nobirths_logistic_growth.ipynb # parent topics for sections must be an index.md file
      - SI model with constant population demographics: tutorials/notebooks/02_SI_wbirths_logistic_growth.ipynb
      - SIS model with no demographics: tutorials/notebooks/03_SIS_nobirths_logistic_growth.ipynb
      - Outbreak size in the SIR model: tutorials/notebooks/04_SIR_nobirths_outbreak_size.ipynb
      - Average age at infection in the SIR model: tutorials/notebooks/05_SIR_wbirths_age_distribution.ipynb
      - Intrinsic periodicity of the SIR system: tutorials/notebooks/06_SIR_wbirths_natural_periodicity.ipynb
      - Exploring the critical community size of an SIR model: tutorials/notebooks/07_SIR_CCS.ipynb
      - The relationship between spatial coupling and incidence correlation in a 2-patch model: tutorials/notebooks/08_2patch_SIR_wbirths_correlation.ipynb
      - Modeling the spread of rabies in one dimension: tutorials/notebooks/09_rabies_diffusion_1D.ipynb
      - Periodicity of measles in England and Wales: tutorials/notebooks/10_England_and_Wales.ipynb
      - England and Wales measles analysis: tutorials/notebooks/EW_analysis.ipynb
      - SEI and SEIS model implementations: tutorials/notebooks/SEI_and_SEIS_implementations.ipynb
      - Explore the vital dynamics births components: tutorials/notebooks/births.ipynb
      - Test constant population components: tutorials/notebooks/constant_pop.ipynb
      - Numba compatible distributions: tutorials/notebooks/distributions.ipynb
      - Grid function examples: tutorials/notebooks/grid_examples.ipynb
      - Explore the vital dynamics mortality components: tutorials/notebooks/mortality.ipynb
      - Explore routine immunization: tutorials/notebooks/ri_exploration.ipynb
      - Seasonality in transmission: tutorials/notebooks/seasonality.ipynb
  - API reference: reference/
  - Code of conduct: code_of_conduct.md
  - Contribution guide: contribute.md
  - What's new: whatsnew.md


# icons, semantic markup, emojis
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list # enables HTMl and CSS classes to inline elements
  - md_in_html # enables grids
  - admonition # warnings, etc.
  - def_list
  - footnotes
  - pymdownx.snippets: # insert content from other files
      auto_append:
        - docs/includes/glossary.md
  - abbr # term/abbreviation hover description
  - pymdownx.emoji: # emojis and icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex: # Latex processing for math equations
      generic: true
  - pymdownx.snippets: # snippet reuse functionality
  - pymdownx.blocks.details: # allows nesting of collapsible code
  - pymdownx.highlight: # syntax highlighting for code blocks
      linenums: true
      default_lang: 'python'
  - pymdownx.inlinehilite # syntax highlighting for inline code
  - pymdownx.superfences: # enables code, diagram fences to be nested in lists, etc.
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.details # collapsible elements
  - pymdownx.tabbed: # tabbed content that can be toggled
      alternate_style: true
  - pymdownx.blocks.caption # captions for images, tables, etc.

# javascript customization for math
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - customization/css/extra.css # custom CSS for footer spacing
plugins:
  - search # search functionality
  - autorefs # automatically create linkable references
  - include-markdown # include other files, such as READMEs
  - table-reader # enables rendering of CSV/TSV files or tables
  - mkdocs-jupyter: # enables Jupyter notebooks to be rendered
      execute: true
      execute_ignore:
        - docs/tutorials/notebooks/07_SIR_CCS.ipynb
        - docs/tutorials/notebooks/10_England_and_Wales.ipynb
      allow_errors: true
      include_source: true
  - gen-files:
      scripts:
        - docs/customization/gen-files.py
  - literate-nav:
      tab_length: 2
  - mkdocstrings: # process docstrings to generate API reference
      handlers:
        python:
          paths: [src] # path to source code
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            heading_level: 2
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: true
            show_object_full_path: true
            preload_modules:
            - laser.core
  - mermaid2
  - exclude:
      glob:
        - customization/gen-files.py # exclude file generation script
        - includes/glossary.md # exclude glossary include file

copyright: Copyright &copy; 2025 Gates Foundation. All rights reserved.

extra:
  generator: false
  footer_links:
    - text: "Privacy and Cookies Notice"
      href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
      href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InstituteforDiseaseModeling/laser-generic # update to your repo
    - icon: fontawesome/regular/envelope
      link: mailto:idm@gatesfoundation.org
    - icon: octicons/globe-24
      link: https://idmod.org
    - icon: simple/youtube
      link: http://www.youtube.com/@institutefordiseasemodelin1987
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/institute-disease-modeling


  analytics:
    provider: custom
    property: GTM-NK4K647
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you like, provide additional information by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
